### ISSUE TITLE
Problems when copying/moving/pasting data

### ISSUE THREAD

**Issue by muxi1** [CompSciOrBust/N-Xplorer#1] opened 2020-01-14 07:51 UTC
Hello @CompSciOrBust 

This is a very good tool, and for me especially when it comes to editing text files! I have tested some file operations.
When copying and then pasting data, N-Xplorer v0.6 always freezes. Moving and pasting a file into a newly created folder works, but nothing happens if you try to move the file from that folder back to its original location. 

Edit:
Sorry, the tool won't freeze. It only takes a very long time to paste a folder to be copied that contains multiple data. Due to a missing status display, as well as the long copy process, I could not judge this correctly at first. 
But as I said, there is a problem with moving files and folders. Files are not moved from a folder to the root level, and folders are not displayed as folders after they are moved to the root level, but as a file with a size of 0B.

My Setting:
AMS 0.10.2 (d5458960)
sysNand 5.1.0 / emuMMC 9.1.0
SD-Card on FAT32

**Comment by CompSciOrBust** [comment] 2020-01-14 16:01
Thanks for the info. I'm going to look in to threading the copy operation and add a pop up window when things are being copied and moved. I'm not sure why things might not move correctly. I'll look in to that too.

**Comment by CompSciOrBust** [comment] 2020-01-14 18:31
I think there was a misunderstanding about how moving files works. Once you move a file the clipboard isn't looking at the new path so this is intended behavior. I think what you were doing makes more sense though so I'll change it so if you move a file it will then also change the path the clipboard has stored. I can't reproduce the bug where folders show as 0 byte files. Could you possibly make a video of you doing it for me?
Edit: Changed how moving files works in [this commit](https://github.com/CompSciOrBust/N-Xplorer/commit/c36de18dcc2f66bdd48ce807f2ee5771c731fd62). It'll be included in the next update or you can compile it yourself now.
Edit 2: I've added a message telling you when files are being copied so you know that the app hasn't frozen. I'll do a git push once I've done some more testing.
Edit 3: After a bit of bug fixing I ended up with [this.](https://github.com/CompSciOrBust/N-Xplorer/commit/50ebfae7b536bae670dde6b3cf1c9b64521c8725) It _should_ work.

**Comment by muxi1** [comment] 2020-01-15 07:56
I can try to make a video. 

Edit:
I hope that you can see in the amateurish video the most important things...
What is shown in the video seems to happen only from time to time, but both, file and folder are displayed with 0B after copying/moving. Sometimes it also happens that, for example, a 4MB file has a smaller size (2MB) after the copy/move operation (but that's not in the video)
https://mega.nz/#!fotgBShY!u-ieU7AncoXsrOtAnNydsQcs3xdD9aWjsbl-aFXwiMA

**Comment by CompSciOrBust** [comment] 2020-01-15 12:53
That video helped. Thanks. I think I have fixed all the bugs you reported but I'll leave the issue open for a few days in case it still happens.

**Comment by muxi1** [comment] 2020-01-15 13:35
Thanks for this update! I am currently testing version 0.6.1 and have found out so far, that the move function is identical to the copy function. So no data is moved, but copied. Continue testing.........

Edit:
I have another suggestion to make the tool exit faster and not always have to do it via Exit from the submenu. For this purpose the - button of the left joy-con would be a good choice.

Edit2:
I also noticed that after an operation, the file/folder is still stored in the clipboard (until a new file/folder is selected for an operation). Is that intended?
Is a file or folder (with its contents) actually overwritten if the same data already exists, or is this data simply skipped?

**Comment by CompSciOrBust** [comment] 2020-01-15 15:54
I'm keeping the minus button reserved for a different menu but maybe I could make double pressing plus exit the app. Yeah it's intended that after a operation the clipboard maintains it's contents, I think it's easier if you accidentally move a file or folder to the wrong location. If the file or folder already exists it will be over written but I plan on making a message appear asking if the user wants to overwrite or skip the file (this only happens for copying not moving). I just haven't gotten around to adding it yet.

**Comment by muxi1** [comment] 2020-01-15 16:24
OK, but is it absolutely necessary to have 2 buttons (+ & Y) with the same function to call up the submenu? In my opinion, the + button is superfluous, because Y is faster and more accessible. So it would be generally better to use the + button to quit the tool, as it is the case with most homebrew tools. 



>  If the file or folder already exists it will be over written but I plan on making a message appear asking if the user wants to overwrite or skip the file (this only happens for copying not moving). I just haven't gotten around to adding it yet.

That would be great and extremely useful

**Comment by CompSciOrBust** [comment] 2020-01-15 17:55
I guess not. It just felt more natural to press + to open the sub menu when I was testing.

**Comment by muxi1** [comment] 2020-01-15 18:02
You are the developer! I can only help to find bugs and make suggestions for improvement.

**Comment by CompSciOrBust** [comment] 2020-01-30 18:57
Looks like no one else has had issues. Closing this.

**Closed as completed by CompSciOrBust** 2020-01-30 18:57 UTC
Labels: bug, enhancement
